/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.41
 * Generated at: 2025-07-02 02:01:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/components/allCss.jsp", Long.valueOf(1751418218684L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1748960437584L));
    _jspx_dependants.put("/components/footer.jsp", Long.valueOf(1751417272739L));
    _jspx_dependants.put("/components/navBar.jsp", Long.valueOf(1751417462229L));
    _jspx_dependants.put("jar:file:/D:/web%20development%2023%20sept/BACK-END/Adv%20Java/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Hospital_Management_System/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Welcome to Medi Homes</title>\r\n");
      out.write("  ");
      out.write("<!-- â Bootstrap CSS -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- â Font Awesome Icons -->\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- â Bootstrap Bundle JS (with Popper for dropdowns) -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    .paint-card {\r\n");
      out.write("      box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("      border-radius: 12px;\r\n");
      out.write("      transition: transform 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .paint-card:hover {\r\n");
      out.write("      transform: translateY(-5px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .carousel-inner img {\r\n");
      out.write("      height: 550px;\r\n");
      out.write("      object-fit: cover;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .section-title {\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      font-size: 2.2rem;\r\n");
      out.write("      margin-bottom: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .team-img {\r\n");
      out.write("      height: 300px;\r\n");
      out.write("      width: 250px;\r\n");
      out.write("      object-fit: cover;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .img-fluid-custom {\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      object-fit: cover;\r\n");
      out.write("      border-radius: 12px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feature-icon {\r\n");
      out.write("      font-size: 1.5rem;\r\n");
      out.write("      color: #28a745;\r\n");
      out.write("      margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    hr {\r\n");
      out.write("      border-top: 2px solid #28a745;\r\n");
      out.write("      width: 50%;\r\n");
      out.write("      margin: 40px auto;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Add Font Awesome and Bootstrap CSS in <head> -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-white shadow-sm border-bottom\">\r\n");
      out.write("  <div class=\"container-fluid px-4\">\r\n");
      out.write("    <a class=\"navbar-brand text-primary fw-bold\" href=\"index.jsp\">\r\n");
      out.write("      <i class=\"fas fa-hospital-symbol me-2\"></i> Medi Homes\r\n");
      out.write("    </a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("      data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\"\r\n");
      out.write("      aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("      <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0 align-items-center\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Not Logged In -->\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Logged In -->\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Carousel -->\r\n");
      out.write("<div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("  <div class=\"carousel-indicators\">\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"0\" class=\"active\"></button>\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"1\"></button>\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"2\"></button>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"carousel-inner\">\r\n");
      out.write("    <div class=\"carousel-item active\">\r\n");
      out.write("      <img src=\"https://images.pexels.com/photos/8460036/pexels-photo-8460036.jpeg\" class=\"d-block w-100\" alt=\"Hospital Doctors\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img src=\"https://images.pexels.com/photos/7580258/pexels-photo-7580258.jpeg\" class=\"d-block w-100\" alt=\"Nurses in hospital\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img src=\"https://images.pexels.com/photos/5327580/pexels-photo-5327580.jpeg\" class=\"d-block w-100\" alt=\"Modern Hospital\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"prev\">\r\n");
      out.write("    <span class=\"carousel-control-prev-icon\"></span>\r\n");
      out.write("    <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"next\">\r\n");
      out.write("    <span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("    <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("  </button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Features -->\r\n");
      out.write("<div class=\"container py-5\">\r\n");
      out.write("  <p class=\"text-center section-title text-success\">Why Choose Medi Homes?</p>\r\n");
      out.write("  <div class=\"row align-items-stretch\">\r\n");
      out.write("    <div class=\"col-md-8\">\r\n");
      out.write("      <div class=\"row g-3\">\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <div class=\"card paint-card h-100\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <p class=\"fs-5 fw-bold\"><i class=\"fas fa-shield-alt feature-icon\"></i>Patient Safety</p>\r\n");
      out.write("              <p>We follow world-class safety protocols and infection control to keep you protected at all times.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <div class=\"card paint-card h-100\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <p class=\"fs-5 fw-bold\"><i class=\"fas fa-hospital feature-icon\"></i>Clean Facilities</p>\r\n");
      out.write("              <p>Our hospital maintains the highest hygiene and sterilization standards in every department.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <div class=\"card paint-card h-100\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <p class=\"fs-5 fw-bold\"><i class=\"fas fa-vials feature-icon\"></i>Cutting-edge Research</p>\r\n");
      out.write("              <p>We actively pursue medical innovation to improve treatments and patient outcomes every day.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <div class=\"card paint-card h-100\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <p class=\"fs-5 fw-bold\"><i class=\"fas fa-user-md feature-icon\"></i>Compassionate Doctors</p>\r\n");
      out.write("              <p>Our certified specialists treat you with expertise, empathy, and personalized attention.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Image Section -->\r\n");
      out.write("    <div class=\"col-md-4 d-flex align-items-center\">\r\n");
      out.write("      <img src=\"https://images.pexels.com/photos/8376174/pexels-photo-8376174.jpeg\" alt=\"Smiling doctor\" class=\"img-fluid-custom w-100\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<!-- Our Team -->\r\n");
      out.write("<div class=\"container py-4\">\r\n");
      out.write("  <p class=\"text-center section-title text-primary\">Meet Our Expert Team</p>\r\n");
      out.write("  <div class=\"row justify-content-center\">\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"col-md-3 mb-4\">\r\n");
      out.write("      <div class=\"card paint-card text-center h-100\">\r\n");
      out.write("        <div class=\"card-body d-flex flex-column align-items-center\">\r\n");
      out.write("          <img src=\"https://images.pexels.com/photos/8460157/pexels-photo-8460157.jpeg\"\r\n");
      out.write("               alt=\"CEO\" class=\"team-img mb-3\">\r\n");
      out.write("          <h5 class=\"fw-bold\">Dr. Samuani Simi</h5>\r\n");
      out.write("          <p class=\"text-muted\">(CEO & Chairperson)</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-md-3 mb-4\">\r\n");
      out.write("      <div class=\"card paint-card text-center h-100\">\r\n");
      out.write("        <div class=\"card-body d-flex flex-column align-items-center\">\r\n");
      out.write("          <img src=\"https://images.pexels.com/photos/5452201/pexels-photo-5452201.jpeg\"\r\n");
      out.write("               alt=\"Head of Research\" class=\"team-img mb-3\">\r\n");
      out.write("          <h5 class=\"fw-bold\">Dr. Anjali Rao</h5>\r\n");
      out.write("          <p class=\"text-muted\">(Head of Research)</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-md-3 mb-4\">\r\n");
      out.write("      <div class=\"card paint-card text-center h-100\">\r\n");
      out.write("        <div class=\"card-body d-flex flex-column align-items-center\">\r\n");
      out.write("          <img src=\"https://images.pexels.com/photos/8376175/pexels-photo-8376175.jpeg\"\r\n");
      out.write("               alt=\"Chief Surgeon\" class=\"team-img mb-3\">\r\n");
      out.write("          <h5 class=\"fw-bold\">Dr. Priya Sharma</h5>\r\n");
      out.write("          <p class=\"text-muted\">(Chief Surgeon)</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-md-3 mb-4\">\r\n");
      out.write("      <div class=\"card paint-card text-center h-100\">\r\n");
      out.write("        <div class=\"card-body d-flex flex-column align-items-center\">\r\n");
      out.write("          <img src=\"https://images.pexels.com/photos/1170979/pexels-photo-1170979.jpeg\"\r\n");
      out.write("               alt=\"Cardiologist\" class=\"team-img mb-3\">\r\n");
      out.write("          <h5 class=\"fw-bold\">Dr. Vivek Mehta</h5>\r\n");
      out.write("          <p class=\"text-muted\">(Cardiologist)</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Footer Example</title>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"container-fluid bg-success text-white py-4\">\r\n");
      out.write("  <div class=\"row text-center text-md-start px-3\">\r\n");
      out.write("    <div class=\"col-md-6 mb-3 mb-md-0\">\r\n");
      out.write("      <h5 class=\"fw-bold\">Developed by Salman & Vishal</h5>\r\n");
      out.write("      <p class=\"mb-1\"> Â© 2025 All rights reserved.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-6\">\r\n");
      out.write("      <h6 class=\"fw-bold\">Contact Us</h6>\r\n");
      out.write("      <p class=\"mb-1\">\r\n");
      out.write("        <i class=\"bi bi-telephone-fill me-2\"></i>\r\n");
      out.write("        <a href=\"tel:+918757359592\" class=\"text-white text-decoration-none\">\r\n");
      out.write("          +91 87573 59592\r\n");
      out.write("        </a><br>\r\n");
      out.write("        <i class=\"bi bi-telephone-fill me-2\"></i>\r\n");
      out.write("        <a href=\"tel:+919060950890\" class=\"text-white text-decoration-none\">\r\n");
      out.write("          +91 90609 50890\r\n");
      out.write("        </a>\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /components/navBar.jsp(22,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userObj}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("          <li class=\"nav-item\">\r\n");
        out.write("            <a class=\"nav-link text-dark\" href=\"admin_login.jsp\">\r\n");
        out.write("              <i class=\"fas fa-user-shield me-1\"></i> Admin\r\n");
        out.write("            </a>\r\n");
        out.write("          </li>\r\n");
        out.write("          <li class=\"nav-item\">\r\n");
        out.write("            <a class=\"nav-link text-dark\" href=\"doctor_login.jsp\">\r\n");
        out.write("              <i class=\"fas fa-user-md me-1\"></i> Doctor\r\n");
        out.write("            </a>\r\n");
        out.write("          </li>\r\n");
        out.write("          <li class=\"nav-item\">\r\n");
        out.write("            <a class=\"nav-link text-dark\" href=\"user_appointment.jsp\">\r\n");
        out.write("              <i class=\"fas fa-calendar-check me-1\"></i> Appointment\r\n");
        out.write("            </a>\r\n");
        out.write("          </li>\r\n");
        out.write("          <li class=\"nav-item\">\r\n");
        out.write("            <a class=\"nav-link text-dark\" href=\"user_login.jsp\">\r\n");
        out.write("              <i class=\"fas fa-user me-1\"></i> User\r\n");
        out.write("            </a>\r\n");
        out.write("          </li>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /components/navBar.jsp(46,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty userObj}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("          <li class=\"nav-item\">\r\n");
        out.write("            <a class=\"nav-link text-dark\" href=\"user_appointment.jsp\">\r\n");
        out.write("              <i class=\"fas fa-calendar-plus me-1\"></i> Appointment\r\n");
        out.write("            </a>\r\n");
        out.write("          </li>\r\n");
        out.write("          <li class=\"nav-item\">\r\n");
        out.write("            <a class=\"nav-link text-dark\" href=\"view_appointment.jsp\">\r\n");
        out.write("              <i class=\"fas fa-list-alt me-1\"></i> View Appointments\r\n");
        out.write("            </a>\r\n");
        out.write("          </li>\r\n");
        out.write("\r\n");
        out.write("          <li class=\"nav-item dropdown\">\r\n");
        out.write("            <a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarDropdown\" role=\"button\"\r\n");
        out.write("              data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
        out.write("              <i class=\"fas fa-user-circle me-1\"></i> ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userObj.fullname}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("            </a>\r\n");
        out.write("            <ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
        out.write("              <li><a class=\"dropdown-item\" href=\"change_password.jsp\">\r\n");
        out.write("                <i class=\"fas fa-key me-2\"></i> Change Password</a>\r\n");
        out.write("              </li>\r\n");
        out.write("              <li><a class=\"dropdown-item\" href=\"userLogout\">\r\n");
        out.write("                <i class=\"fas fa-sign-out-alt me-2\"></i> Logout</a>\r\n");
        out.write("              </li>\r\n");
        out.write("            </ul>\r\n");
        out.write("          </li>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
